name: Deploy to Firebase
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Aktualisierte Version

      - name: Install Node.js
        uses: actions/setup-node@v4  # Aktualisiert auf v4
        with:
          node-version: 20  # Node.js 20 (LTS)

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Nur wenn dein Projekt einen Build benötigt (z.B. React/Vue)

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0  # Offizielle Action
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}  # Nutze den Token aus login:ci
          projectId: deine-projekt-id  # Ersetze mit deiner Firebase-Projekt-ID
          channelId: live